<a href="https://colab.research.google.com/github/rahmasifas/rahmasifa_test/blob/main/day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
umur = 20

In [ ]:
print(umur)

20


In [ ]:
nama = 'arif'

In [ ]:
print(nama)

arif


In [ ]:
# print(alamat)

In [ ]:
nama_lengkap = 'arif romadhan'
nama_lengkap

'arif romadhan'

In [ ]:
listku = ['arif','ari','dery']
listku

['arif', 'ari', 'dery']

In [ ]:
dictku ={
    'nama' : 'arif',
    'gaji' : 1000000

}
dictku

{'nama': 'arif', 'gaji': 1000000}

In [ ]:
dictku['nama']

'arif'

In [ ]:
listku = ['sepatu',1000,'baju',0.5]
listku

['sepatu', 1000, 'baju', 0.5]

In [ ]:
price = 500
quantity = 50

total =price * quantity
total

25000

In [ ]:
nama_ku = 'Arif'
nama_mu = 'dian Satro'

nama_ku + nama_mu

'Arifdian Satro'

In [ ]:
nama_ku.lower()

'arif'

In [ ]:
nama_mu.lower()

'dian satro'

In [ ]:
kita = 'aku dan kamu'

In [ ]:
kita = kita.replace('kamu','dia')

In [ ]:
kita

'aku dan dia'

In [ ]:
phone_number = '+62801-0029-9000'
phone_number

'+62801-0029-9000'

In [ ]:
phone_number = phone_number.replace('+628', '0')
phone_number

'001-0029-9000'

In [ ]:
phone_number = phone_number.replace ('-', '')
phone_number

'00100299000'

In [ ]:
soto = 15000
ketoprak = 12000

In [ ]:
if soto>ketoprak:
  print('akan makan soto')
else:
  print('saya tidak makan')

akan makan soto


In [ ]:
nama1 = 'Arif'
nama2 = 'arif'
nama1==nama2

False

In [ ]:
nama1.lower()==nama2

True

In [ ]:
nama = 'wandi'
age = 12

In [ ]:
nama + str(age)

'wandi12'

In [ ]:
age_ku = 12.0
age_mu = 14

total = age_ku + age_mu
total

26.0

In [ ]:
int(age_ku) + age_mu

26

In [ ]:
listku = ['sepatu',1000,'baju',0.5]
listku

['sepatu', 1000, 'baju', 0.5]

In [ ]:
listku[1]

1000

In [ ]:
listku[1:]

[1000, 'baju', 0.5]

In [ ]:
listku[1:3]

[1000, 'baju']

In [ ]:
listku[-2:]

['baju', 0.5]

In [ ]:
listku

['sepatu', 1000, 'baju', 0.5]

In [ ]:
listku.append('kamu')

In [ ]:
listku

['sepatu', 1000, 'baju', 0.5, 'kamu']

In [ ]:
listku = ['sepatu',1000,[1,[2,3]],'baju',0.5]
listku

['sepatu', 1000, [1, [2, 3]], 'baju', 0.5]

In [ ]:
listku[2][1][1]

3

In [ ]:
listku[2]

[1, [2, 3]]

In [ ]:
listku[2][1]

[2, 3]

In [ ]:
listku[2][1][1]

3

In [ ]:
listku.remove('baju')

In [ ]:
listku

['sepatu', 1000, [1, [2, 3]], 0.5]

In [ ]:
listku  =[1,2,3,4,5]

In [ ]:
len(listku)

5

In [ ]:
x = 5

In [ ]:
del listku[2],listku[3],x

In [ ]:
x

NameError: ignored

In [ ]:
listku

[1, 2, 4]

In [ ]:
listku[1:3]

[2, 4]

In [ ]:
del listku[1:3]

In [ ]:
listku

[1, 5]

In [ ]:
num_list=['12','14',[16,20,30]]
num_list

['12', '14', [16, 20, 30]]

In [ ]:
num_list[2]

[16, 20, 30]

In [ ]:
# num_list[3]

In [ ]:
listku  =[1,2,3,4,5]

In [ ]:
min_v = min(listku)
min_v

1

In [ ]:
max_v = max(listku)
max_v

5

In [ ]:
sum_v = sum(listku)
sum_v

15

In [ ]:
# listku/2

In [ ]:
import numpy as np

In [ ]:
arrku = np.array(listku)
arrku

array([1, 2, 3, 4, 5])

In [ ]:
listku

[1, 2, 3, 4, 5]

In [ ]:
print(arrku)

[1 2 3 4 5]


In [ ]:
listku/2

TypeError: ignored

In [ ]:
arrku/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
listku + listku

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
arrku + arrku

array([ 2,  4,  6,  8, 10])

In [ ]:
arrku.mean()

3.0

In [ ]:
np.median(arrku)

3.0

In [ ]:
numbers=[2,3,6,20,22]
max(numbers) - min(numbers)


20

In [ ]:
# di convert jadi array
np.sum(numbers)

53

In [ ]:
# tetap tipe list
sum(numbers)

53

In [ ]:
numbers=[2,3,6,20,22]
numbers

[2, 3, 6, 20, 22]

In [ ]:
numbers.append(50)

In [ ]:
numbers

[2, 3, 6, 20, 22, 50]

In [ ]:
contoh_dict ={
    'nim' : [1,2,3,4,5,[6,7,8]],
    'nama' : ['arif','budi'],
    'status' : 6,
    'second_dict' : {
              'nim' : [1,2,3,4,5],
              'nama' : ['arif','budi'],
              'status' : 6

              } 
}
contoh_dict

{'nim': [1, 2, 3, 4, 5, [6, 7, 8]],
 'nama': ['arif', 'budi'],
 'status': 6,
 'second_dict': {'nim': [1, 2, 3, 4, 5],
  'nama': ['arif', 'budi'],
  'status': 6}}

In [ ]:
contoh_dict['nama']

['arif', 'budi']

In [ ]:
contoh_dict['nama'][0]

'arif'

In [ ]:
contoh_dict['nim'][5][2]

8

In [ ]:
type(contoh_dict)

dict

In [ ]:
type(contoh_dict['nim'])

list

In [ ]:
brand=['Samsung','Dell','Apple']
stock=[27,20.10]
type_k = ['PC','Laptop','Tablet']


In [ ]:
dict_phone = {
    

}
dict_phone

{}

In [ ]:
dict_phone = {
    'brand':brand,
    'stock':stock,
    'type_k':type_k
}
dict_phone

{'brand': ['Samsung', 'Dell', 'Apple'],
 'stock': [27, 20.1],
 'type_k': ['PC', 'Laptop', 'Tablet']}

In [ ]:
dict.keys(dict_phone)

dict_keys(['brand', 'stock', 'type_k'])

In [ ]:
dict.values(dict_phone)

dict_values([['Samsung', 'Dell', 'Apple'], [27, 20.1], ['PC', 'Laptop', 'Tablet']])

In [ ]:
fruits_dict = {
    "fruit":["Mango", "Banana"],
    "Color":["Blue", "Red"],
    "Quantity":[0,25]
}
fruits_dict

{'fruit': ['Mango', 'Banana'], 'Color': ['Blue', 'Red'], 'Quantity': [0, 25]}

In [ ]:
fruits_dict['Quantity'] = [10,5]

In [ ]:
fruits_dict

{'fruit': ['Mango', 'Banana'], 'Color': ['Blue', 'Red'], 'Quantity': [10, 5]}

In [ ]:
fruits_dict['Quantity'][1] = 20

In [ ]:
fruits_dict

{'fruit': ['Mango', 'Banana'], 'Color': ['Blue', 'Red'], 'Quantity': [10, 20]}

In [ ]:
students={ 
'name':['Budi','Jessica'],
'age':[19,24]
}

students


{'name': ['Budi', 'Jessica'], 'age': [19, 24]}

In [ ]:
students.update({'loc':['bdg','jkt']})


In [ ]:
students

{'name': ['Budi', 'Jessica'], 'age': [19, 24], 'loc': ['bdg', 'jkt']}

In [ ]:
students['loc'].append('sby')

In [ ]:
students

{'name': ['Budi', 'Jessica'], 'age': [19, 24], 'loc': ['bdg', 'jkt', 'sby']}

In [ ]:
students['name'].append('ammar')

In [ ]:
students

{'name': ['Budi', 'Jessica', 'ammar'],
 'age': [19, 24],
 'loc': ['bdg', 'jkt', 'sby']}

In [ ]:
students['name'].remove("Jessica")

In [ ]:
students

{'name': ['Budi', 'ammar'], 'age': [19, 24], 'loc': ['bdg', 'jkt', 'sby']}

In [ ]:
del students['age']

In [ ]:
students

{'name': ['Budi', 'ammar'], 'loc': ['bdg', 'jkt', 'sby']}

In [ ]:
Students={ 
'name':['Budi','Jessica']
'age':[19,24]
}
